development:
  adapter: mysql
  host: localhost
  user: root
  password:
  database: trails

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql
  host: localhost
  user: root
  password:
  database: trails